apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - "./infra/k8s/*"
build:
  googleCloudBuild:
    projectId:  nodejs-with-microservices
  artifacts:
    - image: asia.gcr.io/nodejs-with-microservices/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'